name: futbol_tahmin
description: Online maç istatistik ve tahmin uygulaması
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.6
  provider: ^6.1.2
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.3
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
